In [1]:
import numpy as np

# Creating an array

In [2]:
a = np.array([1,2,3]) #1 dimensional array
a

array([1, 2, 3])

In [3]:
b = np.array([[1,2,3],[4,5,6]]) #2 dimensional array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #3 dimensional array
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# Inspecting array

In [5]:
a.shape #getting the array shape

(3,)

In [6]:
b.shape

(2, 3)

In [7]:
c.shape

(1, 3, 3)

In [8]:
len(a) #length of the array

3

In [9]:
len(b)

2

In [10]:
len(c)

1

In [11]:
a.ndim #getting the dimension of the array

1

In [12]:
b.ndim

2

In [13]:
c.ndim

3

In [14]:
a.size #number of elements

3

In [15]:
b.size

6

In [16]:
c.size

9

In [17]:
a.dtype #data type of the elements 

dtype('int32')

In [18]:
b.dtype

dtype('int32')

In [19]:
c.dtype

dtype('int32')

In [20]:
a.itemsize #each item size in bytes

4

In [21]:
b.itemsize

4

In [22]:
c.itemsize

4

In [23]:
a.nbytes #total size of the array in bytes

12

In [24]:
b.nbytes

24

In [25]:
c.nbytes

36

# Slicing and Indexing

In [26]:
a[2] #getting 3rd element of array a

3

In [27]:
b[1,2] #getting the element of 2nd row and 3rd column [r,c]

6

In [28]:
c[0,1,2] #3 dimensions

6

In [29]:
a[1:] #getting from 2nd element to the last

array([2, 3])

In [30]:
b[:, 0] # getting complete 1st column

array([1, 4])

In [31]:
b[1,:] #geting complete 2nd row

array([4, 5, 6])

In [32]:
b[:, 1:] #getting 2,3,5,6

array([[2, 3],
       [5, 6]])

In [33]:
#we can also use stepsize in slicing if we wanted to

# Initializing different types of array

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.full((3,3), 2) #creating a matrix full of 2's with shape 3x3

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [37]:
np.full_like(b, 3) #copy the shape of matrix b but fill it up with 3

array([[3, 3, 3],
       [3, 3, 3]])

In [38]:
np.random.rand(3,3) #a matrix of shape 3x3 with values between 0-1

array([[0.0404541 , 0.97040256, 0.15482898],
       [0.97339608, 0.88284111, 0.08929782],
       [0.78935768, 0.72448503, 0.46110528]])

In [39]:
np.random.randint(1,11, size=(3,3)) #shape 3x3 and values between 1 to 10

array([[6, 8, 5],
       [9, 3, 8],
       [9, 8, 2]])

In [40]:
np.eye(5) #identity matrix with 5x5 shape

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Copying

In [41]:
#in numpy if we use x = y to copy matric y into x that might cause problems because it actually doesn't copy the matrix
#just copies the memory location. As a result all the changes we make to matrix x will also be done with matrix y.
#so, be careful

In [42]:
x = b.copy() #to avoid the above problem we use copy function
x

array([[1, 2, 3],
       [4, 5, 6]])

# Mathematics

In [43]:
b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [44]:
b - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [45]:
b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [46]:
b / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [47]:
b ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [48]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

# Linear Algebra

In [49]:
d = np.array([[1,2], [3,4], [5,6]])
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.matmul(b,d) #matrix multiplication

array([[22, 28],
       [49, 64]])

In [51]:
e = np.eye(5)    #determinants
np.linalg.det(e)

1.0

# Statistics

In [52]:
np.min(b) #minimum of all the elements

1

In [53]:
np.min(b, axis=1) #minimum in each row

array([1, 4])

In [54]:
np.min(b, axis=0) #minimum in each columns

array([1, 2, 3])

In [55]:
np.max(b) #maximum of all the elements

6

In [56]:
np.max(b, axis=1) #maximum in each row

array([3, 6])

In [57]:
np.max(b, axis=0) #maximum in each column

array([4, 5, 6])

In [58]:
np.mean(b) #similar to min and max

3.5

In [59]:
np.median(b) #similar to min and max

3.5

In [60]:
np.corrcoef(b) #correlation coefficient

array([[1., 1.],
       [1., 1.]])

In [61]:
np.std(b) #standard deviation

1.707825127659933

# Others

In [62]:
b.reshape(3,2) #changing the shape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
b > 5 #boolean masking

array([[False, False, False],
       [False, False,  True]])